### ISSUE TITLE
Upload global proteomics data to synapse

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/earlyLateAMLresistance#1]
Upload the metadata, proteomics, and phosphoproteomics files  to synapse (https://www.synapse.org/#!Synapse:syn25572229), commit processing code here. Then use the P3 code to merge them to two synapse tables.

**Comment by mdnestor** [comment]
Just uploaded all the global+phospho crosstabs, and made a pull request: https://github.com/PNNL-CompBio/earlyLateAMLresistance/pull/3
