### ISSUE TITLE
Map metadata to global and phospho proteomics and upload to synapse table

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/earlyLateAMLresistance#2]
Once the data has been uploaded (#1) we can upload to Synapse. 

This is the template for data processing:
https://github.com/PNNL-CompBio/p3/blob/main/dataProcessing/proteomicDataProcessing.Rmd

**Comment by CamiloPosso** [comment]
Hi Sara. Looking at the metadata table, I see the following columns.

Sample ID: Unique sample identifier
Plex: Plex ID
Channel: TMT channel
Loading Mass: I'm not sure of the meaning of this one, but it has numeric entries from about 50 to 200.
PNNL ID: Another unique sample identifier
BeatAML Patient ID: These are not unique to the samples. Some are numbers, others strings (Cell Line)
Tx Status: This one is the most cryptic. About half the entries are missing here. I can go into more detail about these entries here if you want.

**Comment by sgosline** [comment]
I'm assuming that patient id is some number like 15-632111? I think the first 2 correspond to year. 
Let's collect Sample ID, Loading Mass, patient ID and tx status (as string),  Ithink those should be distinct, correct?

**Comment by sgosline** [comment]
Looks like this is complete, closing.
